version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'




  #redis:
      #image: 'bitnami/redis:latest'
      #environment:
               # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
                #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      #ports:
      #- '6379:6379'